services:

  mariadb:

    image: mariadb:10.4.32

    container_name: apiarticulos-db

    restart: unless-stopped

    ports:
      - "${MARIADB_PORT}:3306"

    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}

    volumes:
      - mariadb_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

    networks:
      - apiarticulos-network

volumes:
  mariadb_data:

networks:
  apiarticulos-network: